export type Methods = 'get' | 'post' | 'patch' | 'put' | 'delete' | 'head' | 'options'

export const GET = 'GET'
export const POST = 'POST'
export const PUT = 'PUT'
export const PATCH = 'PATCH'
export const DELETE = 'DELETE'
export const HEAD = 'HEAD'
export const OPTIONS = 'OPTIONS'
export const CONNECT = 'CONNECT'
export const TRACE = 'TRACE'
